### ISSUE TITLE
US3.9 Arduino to Raspberry Pi

### ISSUE THREAD

**Issue by nugyn** [PGP1/arduino-microcontroller#4]

**Comment by nugyn** [comment]
This issue is regarding how we can best control sensor collection, and then serial comms with RPI. @inci90 it was mentioned we build a 'monofile' tag the sensor data then send the RPI for parsing.

**Comment by ijkeleher** [comment]
hey @nugyn so i'm currently looking into this approach: 

https://create.arduino.cc/projecthub/8bitkick/sensor-data-streaming-with-arduino-683a6c#toc-outputting-json-log-via-usb-2

the data is streamed to the pi via JSON, the pi captures the JSON data and then opens its own stream. i had a call with austin just then discussing the pub/sub model. 

i think the best approach right now is to get *some* data either dummy or live into the s3 bucket from the arduino just to get the data pipeline online. i'm looking at some quick and dirty approaches via the AWS s3 SDK or a simple TCP socket stream.

then next sprint we can refactor for a more optimal approach that scales well. 

as the model training team will be going ahead with their own generated dummy data i think we can leave the CSV transformation until next sprint as well.

**Comment by auspham** [comment]
any US for this?

**Comment by ijkeleher** [comment]
@rockmanvnx6 1.5

**Comment by nugyn** [comment]
Okay we need to split this task into smaller pieces, so we don't create conflicts. Do you want to take ownership over this part, as I need more tasks to do moving forward.
